default_language_version:
  python: "3.12"
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pdm-project/pdm
    rev: 2.10.4
    hooks:
      - id: pdm-lock-check
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.6"
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        exclude: "tests/openapi/typescript_converter/test_converter"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        exclude: "_templates|.git|.all-contributorsrc"
  - repo: https://github.com/python-formate/flake8-dunder-all
    rev: v0.3.1
    hooks:
      - id: ensure-dunder-all
        exclude: "test*|examples*|tools"
        args: ["--use-tuple"]
  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.17.1
    hooks:
      - id: slotscheck
        exclude: "test_*|docs"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.7.1"
    hooks:
      - id: mypy
        exclude: "tools|docs"
        additional_dependencies: ["litestar[standard]", pytest]
