name: Test

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      coverage:
        required: false
        type: boolean
        default: false
      os:
        required: false
        type: string
        default: "ubuntu-latest"

jobs:
  test:
    runs-on: ${{ inputs.os }}
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - uses: pdm-project/setup-pdm@v3
        name: Set up PDM
        with:
          python-version: ${{ inputs.python-version }}
          allow-python-prereleases: true
          cache: true

      - name: Install dependencies
        run: pdm install

      - name: Set python PATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Test
        if: ${{ !inputs.coverage }}
        run: |
          pdm run pytest

      - name: Test with coverage
        if: inputs.coverage
        run: pdm run pytest docs/examples tests --cov=src --cov-report=xml

      - uses: actions/upload-artifact@v4
        if: inputs.coverage
        with:
          name: coverage-xml
          path: coverage.xml
